# Generated by Django 5.2 on 2025-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_two_step_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
