# Generated by Django 5.2 on 2025-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_emergency_contact_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=154, null=True),
        ),
    ]
