# Generated by Django 5.2 on 2025-04-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driver_address_driver_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
    ]
