# Generated by Django 5.2 on 2025-04-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_driver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ledger_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
