# Generated by Django 5.2 on 2025-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bus_data',
            field=models.JSONField(blank=True, help_text='Store bus data as JSON.', null=True),
        ),
    ]
