# Generated by Django 5.2 on 2025-04-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_ledger_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ledger_balance',
        ),
    ]
