# Generated by Django 5.2 on 2025-04-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buslocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
