# Generated by Django 5.2 on 2025-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_ledger_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ledger_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
