# Generated by Django 5.2 on 2025-05-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='company',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
