# Generated by Django 5.2 on 2025-05-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='contact_info',
        ),
    ]
