# Generated by Django 5.2 on 2025-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_driver_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
