# Generated by Django 5.2 on 2025-05-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_driver_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
    ]
