# Generated by Django 5.2 on 2025-05-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_company_alter_driver_company_route_specific_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Specific_Bus',
        ),
    ]
