# Generated by Django 5.2 on 2025-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bus_delete_specific_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
