# Generated by Django 5.2 on 2025-05-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_delete_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='map_coordinates',
        ),
    ]
