# Generated by Django 5.2 on 2025-05-01 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_route_map_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='map_coordinates',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
