# Generated by Django 5.2 on 2025-05-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_route_map_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='company',
        ),
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
    ]
