# Generated by Django 5.2 on 2025-05-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_route_company_remove_route_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='about_profile',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
