# Generated by Django 5.2 on 2025-05-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='intermediate_stops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Current_Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.route')),
            ],
        ),
    ]
