# Generated by Django 5.2 on 2025-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_locations_remove_userprofile_ledger_balance_ride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
