# Generated by Django 5.2 on 2025-05-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_ride_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ledger_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
