# Generated by Django 5.2 on 2025-05-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_ride_ledger_balance_delete_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='route',
            name='BusStop',
            field=models.ManyToManyField(blank=True, to='accounts.busstop'),
        ),
    ]
