# Generated by Django 5.2 on 2025-05-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_busstop_delete_locations_route_busstop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='BusStop',
            new_name='bus_stop',
        ),
    ]
