# Generated by Django 5.2 on 2025-05-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_busstop_route_bus_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus_stop',
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backward_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backward_station', to='accounts.busstop')),
                ('forwatd_stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwatd_stations', to='accounts.busstop')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busstop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.path'),
        ),
        migrations.DeleteModel(
            name='Current_Bus',
        ),
    ]
