# Generated by Django 5.2 on 2025-05-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_route_bus_stop_path_route_bus_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='backward_station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='backward_station', to='accounts.busstop'),
        ),
        migrations.AlterField(
            model_name='path',
            name='forwatd_stations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forwatd_stations', to='accounts.busstop'),
        ),
    ]
