# Generated by Django 5.2 on 2025-05-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_path_backward_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus_path',
        ),
        migrations.AddField(
            model_name='route',
            name='backward_station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='backward_station', to='accounts.busstop'),
        ),
        migrations.AddField(
            model_name='route',
            name='forwatd_stations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forwatd_stations', to='accounts.busstop'),
        ),
        migrations.AddField(
            model_name='route',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='accounts.busstop'),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
