# Generated by Django 5.2 on 2025-05-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_route_bus_path_route_backward_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='backward_station',
            new_name='next_station',
        ),
        migrations.RemoveField(
            model_name='route',
            name='forwatd_stations',
        ),
    ]
