# Generated by Django 5.2 on 2025-05-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rename_backward_station_route_next_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='next_station',
        ),
        migrations.AddField(
            model_name='busstop',
            name='next_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
