# Generated by Django 5.2 on 2025-04-20 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('stoppage1', models.CharField(max_length=100)),
                ('stoppage2', models.CharField(max_length=100)),
                ('stoppage3', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('vacant_seats', models.PositiveIntegerField()),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
